version: 0.2

phases:
  install:
    runtime-versions:
      docker: 18
      dotnet: 3.1
    commands:
      - pip install aws-sam-cli
  build:
    commands: 
      - dotnet build -c Release
      - dotnet test -c Release
artifacts:
  files:
    - '**/*'