version: 0.2

phases:
  install:
    runtime-versions:
      docker: 18
      dotnet: 3.1
    commands:
      - pip install aws-sam-cli
      - dotnet tool install -g Amazon.Lambda.Tools
  build:
    commands: 

      #UI Deployments
      - cd ./UI

      - cd SenderApi
      - dotnet restore
      - dotnet lambda deploy-serverless --configuration Release --region sa-east-1 --s3-bucket deploy-teste-dojo --s3-prefix SenderApi --stack-name sender-functions --template serverless.yml