AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:
  KeyValueTable:
    Type: AWS::DynamoDB::Table
    Properties: 
      TableName: KeyValue
      AttributeDefinitions: 
        - AttributeName: Key
          AttributeType: S
      KeySchema: 
        - AttributeName: Key
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
      TimeToLiveSpecification:
        AttributeName: TimeToLive
        Enabled: true